# Generated by Django 5.0.8 on 2024-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Testifier's name", max_length=150)),
                ('job_description', models.CharField(max_length=250)),
                ('feedback', models.TextField()),
                ('image', models.ImageField(upload_to='testifier-image')),
            ],
        ),
    ]
