# Generated by Django 5.0.8 on 2024-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.JSONField(default=list),
        ),
    ]
