# Generated by Django 5.0.8 on 2024-08-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='timestamp',
            new_name='created',
        ),
    ]
