# Generated by Django 5.0.8 on 2024-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_display', models.ImageField(blank=True, null=True, upload_to='career-path-images/')),
                ('career_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.CharField(max_length=350)),
                ('rating', models.DecimalField(decimal_places=1, help_text='i.e. 4.5', max_digits=3)),
                ('language', models.CharField(max_length=20)),
                ('enroll_now_link', models.CharField(max_length=150)),
                ('what_you_will_learn_list', models.JSONField(default=list)),
                ('skills_you_will_gain', models.JSONField(default=list)),
                ('potential_jobs', models.JSONField(default=list)),
            ],
        ),
    ]
