# Generated by Django 5.0.8 on 2024-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('rating', models.CharField(help_text='i.e. 4.5', max_length=3)),
                ('language', models.CharField(max_length=20)),
                ('enroll_now_link', models.TextField()),
                ('what_you_will_learn_list', models.JSONField(default=list)),
                ('skills_you_will_gain', models.JSONField(default=list)),
                ('potential_jobs', models.JSONField(default=list)),
            ],
        ),
    ]
