# Generated by Django 5.0.8 on 2024-11-04 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='course_start_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 4, 10, 9, 51, 78883, tzinfo=datetime.timezone.utc), help_text='Date course starts'),
        ),
    ]
