# Generated by Django 5.0.8 on 2024-08-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='enroll_now_link',
            field=models.CharField(max_length=150),
        ),
    ]
