# Generated by Django 5.0.8 on 2024-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0002_alter_careerpath_enroll_now_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='i.e. 4.5', max_digits=3),
        ),
    ]
