# Generated by Django 5.0.8 on 2024-08-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0003_alter_careerpath_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='img_display',
            field=models.ImageField(blank=True, null=True, upload_to='career-path-images/'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
