# Generated by Django 5.0.8 on 2024-11-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedPlan', models.CharField(max_length=150)),
                ('careerPathName', models.CharField(max_length=150)),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('jobTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('subscribe', models.CharField(blank=True, max_length=3, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
